### ISSUE TITLE
Addition of trigger_offsets instead of horizontal_offset in sequence mode

### ISSUE THREAD

**Issue by Shruti-Tajne** [sibartel/lecroyutils#6]
Hello there, **Thank you** so much for the amazing work! It saved me a lot of time and effort!

I use an older scope (WaveRunner 6100A) to save around 80 segments. I had also downloaded a LeCroy tool called WaveStudio for the purpose of acquiring and analyzing waveform before I found your script.

I noticed 2 things that I wanted to bring your attention to:

1. When I save waveform through their WaveStudio utility and try to parse it using lecroyutils, I got an error saying "UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 12: ordinal not in range(128)."
My crude solution to it was to simply change the encoding type from 'ascii' to 'latin_1', and it works perfectly fine. I am not sure if this matters to anyone else, just wanted to bring your attention to it.

2.  In data.py, on line 128, the code adds horizontal_offset to all the segments. As per my understanding it should be adding the trigger_offsets array instead of one constant value to all segments. 
I noticed the difference when I compared time data from lecroyutils vs from WaveStudio.
I removed the "+ self_horizontal_offset" and added "+ self.trigger_offsets.reshape((-1,1))" in the end on line 130, to resolve the difference.

Again, it's such a minute difference that it might not even matter, but I created an issue just in case.

**Thanks again!
Keep up the good work!**

**Comment by L1nKinc** [comment]
Hi,
thank you for your input and detailed analysis!

1. As I don't use WaveStudio I can't say anything reliable about the encoding issue. Lecroyutils should be compatible to the 'Lecroy waveform template 2.3' (can be downloaded [here](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=http://forums.ni.com/attachments/ni/60/4652/2/LeCroyWaveformTemplate_2_3.pdf&ved=2ahUKEwiC0rrnlMmFAxUnR_EDHb9yCVcQFnoECBUQAQ&usg=AOvVaw16yAzA73H1mSvQwLzNYtNs)). I could not find anything about encoding different from 'ascii'. So maybe WaveStudio does use another lecroy template? Did you check the 'template_name' of the WaveStudio file?
2. That is a good catch! I'm not quite sure why the oscilloscope stores different horizontal_offsets to the trigger times in sequence mode, but it has to be some hardware processing, that can take a little bit different time at each trigger event. So i agree, that the array "trigger_offsets" has to be added instead of the constant "horizontal_offset" which was set at the oscilloscope. Your code proposal seems good to me. I did some testing and found that the discrepancy is always below one time sample of the oscilloscope. So for example with a 2.5 GS acquisition rate the sampling period is 0.4 ns. The time differences of the "trigger_offsets" array to the constant offset was always below that. So as you mentioned, it's a minute difference, but it could be important to some measurements.

Do you want to create a pull request with your change for the offset issue? If not I can do it too.

Best regards
Markus

**Comment by Shruti-Tajne** [comment]
Hi Markus,

1. Thanks for your input! I double-checked the template name, and it's indeed the same. However, there are a few minor differences, like the omission of the first 4 letters 'ALL,' which might have caused the encoding error to show up. Nevertheless, I don't believe any changes are necessary to the code itself.

2. Thanks for understanding! Since I am not very familiar with GitHub processes, I'd prefer if you could handle the changes.

Thanks and Best,
Shruti

**Comment by L1nKinc** [comment]
Hi Shruti,
1. Ok thanks for the info. I'll have an eye on that issue. Maybe someone else, who is using WaveStudio, can verify the encoding issue. Then we can change the code accordingly.
2. All right, I'll do the pull request. Thanks for the hint again!
Best regards,
Markus

**Comment by sibartel** [comment]
@L1nKinc thanks for following up on issue 2 and creating the pull request. I merged it and published a new version v4.0.2.

@Shruti-Tajne thanks for reporting the issues. Could you provide me with such a saved waveform from WaveStudio for which the UnicodeDecodeError is thrown? I would like to investigate this a bit more.

**Comment by Shruti-Tajne** [comment]
Hello again,

Thanks for the update!
Sure, here you go, these are some waveforms saved using WaveStudio. I apologize for the delay.

Thanks and Best,
Shruti
[wavestudio.zip](https://github.com/sibartel/lecroyutils/files/15178102/wavestudio.zip)
